/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewPersonas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonas
     */
    public ViewPersonas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlb_id_persona = new javax.swing.JLabel();
        jlb_nombre_persona = new javax.swing.JLabel();
        jlb_telefono_persona = new javax.swing.JLabel();
        jlb_email_persona = new javax.swing.JLabel();
        jtf_id_persona = new javax.swing.JTextField();
        jtf_nombre_persona = new javax.swing.JTextField();
        jtf_telefono_persona = new javax.swing.JTextField();
        jtf_email_persona = new javax.swing.JTextField();
        jsp_display_controls = new javax.swing.JSeparator();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(51, 51, 51));

        jlb_id_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_id_persona.setForeground(new java.awt.Color(204, 204, 204));
        jlb_id_persona.setText("ID:");

        jlb_nombre_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_nombre_persona.setForeground(new java.awt.Color(204, 204, 204));
        jlb_nombre_persona.setText("Nombre:");

        jlb_telefono_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_telefono_persona.setForeground(new java.awt.Color(204, 204, 204));
        jlb_telefono_persona.setText("Teléfono:");

        jlb_email_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_email_persona.setForeground(new java.awt.Color(204, 204, 204));
        jlb_email_persona.setText("Email:");

        jtf_id_persona.setBackground(new java.awt.Color(102, 102, 102));
        jtf_id_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_id_persona.setForeground(new java.awt.Color(255, 255, 255));

        jtf_nombre_persona.setBackground(new java.awt.Color(102, 102, 102));
        jtf_nombre_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_nombre_persona.setForeground(new java.awt.Color(255, 255, 255));

        jtf_telefono_persona.setBackground(new java.awt.Color(102, 102, 102));
        jtf_telefono_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_telefono_persona.setForeground(new java.awt.Color(255, 255, 255));

        jtf_email_persona.setBackground(new java.awt.Color(102, 102, 102));
        jtf_email_persona.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_email_persona.setForeground(new java.awt.Color(255, 255, 255));

        jbtn_primero.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_primero.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setText("|<");

        jbtn_ultimo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_ultimo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setText(">|");

        jbtn_anterior.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_anterior.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setText("Anterior");

        jbtn_siguiente.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_siguiente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setText("Siguiente");

        jbtn_agregar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_agregar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");

        jbtn_modificar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_modificar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_modificar.setText("Modificar");

        jbtn_nuevo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_nuevo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setText("Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlb_id_persona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_id_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlb_nombre_persona)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_nombre_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlb_telefono_persona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_telefono_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlb_email_persona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_email_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jsp_display_controls)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_id_persona)
                    .addComponent(jtf_id_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nombre_persona)
                    .addComponent(jtf_nombre_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_telefono_persona)
                    .addComponent(jtf_telefono_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_email_persona)
                    .addComponent(jtf_email_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jsp_display_controls, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_ultimo)
                    .addComponent(jbtn_anterior)
                    .addComponent(jbtn_siguiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificar)
                    .addComponent(jbtn_agregar)
                    .addComponent(jbtn_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jbtn_nuevo)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jlb_email_persona;
    public javax.swing.JLabel jlb_id_persona;
    public javax.swing.JLabel jlb_nombre_persona;
    public javax.swing.JLabel jlb_telefono_persona;
    public javax.swing.JSeparator jsp_display_controls;
    public javax.swing.JTextField jtf_email_persona;
    public javax.swing.JTextField jtf_id_persona;
    public javax.swing.JTextField jtf_nombre_persona;
    public javax.swing.JTextField jtf_telefono_persona;
    // End of variables declaration//GEN-END:variables
}
